### PR TITLE
Make dcli devDependency as it is for generating packs

### PR DESCRIPTION
**Pull request by mennovanhout**
1. Bumping dependency versions.
2. Changed dcli and args into devDependencies as they are for creating packs

Currently this package is witholding other packages due constraints of dcli

### CODE REVIEW

**Comment by Ahmadre** [comment]
Thank you so much for your PR! 

I will also have a look at the `wait_for` bug, or was is due to dcli package?

**Comment by mennovanhout** [comment]
> Thank you so much for your PR!
> 
> I will also have a look at the `wait_for` bug, or was is due to dcli package?

That one is still there, i was checking it out but didn't get to it yet!

**Comment by Ahmadre** [comment]
`dcli` and `args` were not in dev_dependencies, because once a user installed this package it should be shipped to generate packs. I have to revert this.

**Comment by Ahmadre** [comment]
i will update the dependencies and fix everything.

**Comment by Ahmadre** [comment]
Fixed dcli package for the `wait_for` bug.

**Pull request merged**
