### PR TITLE
fix: Remove deprecated flutter MaterialIcons (six_ft_apart)

### PR DESCRIPTION
**Pull request by hoxuanvinh1999**

### CODE REVIEW

**Comment by Ahmadre** [comment]
@hoxuanvinh1999 Thank your for your PR :)

could you please remove the lines completely?

Thanks :)

**Comment by eliudio** [comment]
Any ETA?

**Comment by hoxuanvinh1999** [comment]
> @hoxuanvinh1999 Thank your for your PR :)
> 
> could you please remove the lines completely?
> 
> Thanks :)

I did that, thanks for the reply :+1:

**Comment by Ahmadre** [comment]
> > @hoxuanvinh1999 Thank your for your PR :)
> 
> > 
> 
> > could you please remove the lines completely?
> 
> > 
> 
> > Thanks :)
> 
> 
> 
> I did that, thanks for the reply :+1: 

Thanks! Its merged. I'll release a new version asap :)

**Comment by nstrelow** [comment]
Please release a new version @Ahmadre :D

**Comment by stefanpopescu** [comment]
@Ahmadre can you please release a new version 🥲 ?

**Pull request merged**
